<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Etudiant extends Model
{

    protected $fillable = ['nom'];


   /* protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($el){
            Inscription::create([
                'name'=>$el->nom,
                'email'=>$el->email,
                'password'=>bcrypt($el->password),
            ]);

        });



    }*/
}
