<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Inscription extends Model
{
    //
    protected $guarded = ['id'];

    public function etudiant(){
        return $this->belongsTo(Etudiant::class)->orderBy('nom')->orderBy('prenoms')->orderBy('date_nsce');
    }

    public function filiere(){
        return $this->belongsTo(Filiere::class);
    }

    public function cycle(){
        return $this->belongsTo(Cycle::class);
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($inscription){
            $filiereId = $inscription->filiere_id;
            $cycleId = $inscription->cycle_id;
            $etudiantId = $inscription->etudiant_id;
            $anneeId = $inscription->annee_id;

            $semestres = Semestre::where('cycle_id',$cycleId)->get();
            $credits = Credit::with('matiere.ue')->where('filiere_id',$filiereId)->whereIn('semestre_id',$semestres)->get();

            foreach ($credits as $credit){
                Note::create([
                    'inscription_id'=>$inscription->id,
                    'annee_id'=>$inscription->annee_id,
                    'etudiant_id'=>$inscription->etudiant_id,
                    'credit_id'=>$credit->id,
                    'matiere_id'=>$credit->matiere_id,
                    'filiere_id'=>$credit->filiere_id,
                    'semestre_id'=>$credit->semestre_id,
                    'credits'=>$credit->credits,
                    'ue_id'=>$credit->matiere->ue_id,
                ]);
            }


            /*$an = new Annee();
            $an->annee = "2000";
            $an->save();*/
        });
    }
}
